Repository 1stLunchVote/1stLunchVote_Flutter, pull requests merged in 2022-12, with the labels that each got.

#11 [Impl] FCM Token 추가 및 프로필 화면 연동
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  assets/images/food_default.png
  lib/controller/login_controller.dart
  lib/controller/profile_controller.dart
  lib/main.dart
  lib/model/login/user_info.dart
  lib/model/login/user_info.g.dart
  lib/model/profile/profile_info.dart
  lib/model/profile/profile_info.g.dart
  lib/model/vote/vote_item_notifier.dart
  lib/repository/lunch_vote_service.dart
  lib/repository/lunch_vote_service.g.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/login_screen.dart
  lib/view/screen/profile_screen.dart
  lib/view/screen/vote/result_screen.dart
  lib/view/screen/vote/second_vote_screen.dart
  lib/view/widget/second_vote_tile.dart
  lib/view/widget/utils/shared_pref_manager.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, update

#13 [ADD] 실시간 투표 연동 및 결과 화면 연동
  lib/controller/result_controller.dart
  lib/controller/second_vote_controller.dart
  lib/model/vote/final_result.dart
  lib/model/vote/second_vote.dart
  lib/repository/lunch_vote_service.dart
  lib/repository/lunch_vote_service.g.dart
  lib/view/screen/vote/result_screen.dart
  lib/view/screen/vote/second_vote_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: update

#18 [Impl] 그룹 참여
  lib/controller/home_controller.dart
  lib/main.dart
  lib/model/group/group_create.g.dart
  lib/model/group/group_info.g.dart
  lib/model/group/group_join_response.dart
  lib/model/group/user_search.g.dart
  lib/model/group_id_notifier.dart
  lib/repository/lunch_vote_service.dart
  lib/view/screen/home_screen.dart
  pubspec.lock
Labels: update

#17 [IMPL] group invite 개발중
  lib/controller/group_controller.dart
  lib/model/group/group_create.dart
  lib/model/group/user_invite.dart
  lib/model/group/user_search.dart
  lib/repository/lunch_vote_service.dart
  lib/view/screen/group/group_screen.dart
  lib/view/screen/home_screen.dart
  lib/view/widget/group_user.dart
Labels: enhancement

#20 [IMPL] Template Creation
  lib/controller/template_controller.dart
  lib/model/template/template_info.dart
  lib/model/template/template_notifier.dart
  lib/repository/lunch_vote_service.dart
  lib/view/screen/group/group_screen.dart
  lib/view/screen/home_screen.dart
  lib/view/screen/template/template_screen.dart
  lib/view/widget/template_tile.dart
Labels: enhancement
